name: Release patch version

on:
  push:
    branches:
      - 'release-*'
    paths:
      - 'charts/**'

jobs:
  release-chart:
    name: "Release chart for minor version"
    uses: ./.github/workflows/release-chart.yaml